select = ["ALL"]
ignore = [
    "C901", #Checks for functions with a high `McCabe` complexity.
    "D100", #Checks for undocumented public module definitions.
    "D101", #Checks for undocumented public class definitions.
    "D103", #Checks for undocumented public function definitions.
    "D104", #Checks for undocumented public package definitions.
    "D107", #Checks for public `__init__` method definitions that are missing docstrings.
    "E501", #Checks for lines that exceed the specified maximum character length.
    "G003", #Checks for uses string concatenation via the + operator to format logging messages.
    "N999", #Checks for module names that do not follow the `snake_case` naming convention or are otherwise invalid.
    "PLC0206", #Checks for dictionary iterations that extract the dictionary value via explicit indexing, instead of using `.items()`.
    "PLR0915", #Checks for functions or methods with too many statements.
    "PTH103", #Checks for uses of `os.makedirs`.
    "PTH123", #Checks for uses of the `open()` builtin.
    "PTH120", #Checks for uses of `os.path.dirname`.
    "RUF015", #Checks the constructs which can be replaced by next(iter(...)).
    "PERF401", #Checks for `for` loops that can be replaced by a list comprehension.
]
target-version = "py39" #Set minimum version to 3.9 due to Anki still shipping 3.9 in windows packages as of 24.11 (Nov 26, 2024)

[lint.per-file-ignores]
"logger.py" = [
    "SIM105",
    "T201",
    "BLE001",
    "S110",
]
